import {
  Business,
  StaffUser,
  Customer,
  Conversation,
  Message,
  Product,
  Order,
  Service,
  Booking,
  Faq,
  OptOut
} from '../types';

export const INITIAL_BUSINESS: Business = {
  id: 'biz_01',
  name: 'Brew & Botanica Artisans',
  phone: '+234 *** *** 9901',
  category: 'Specialty Coffee, Tea & Herbal Workshop',
  currency: 'USD',
  currencySymbol: '$',
  address: '14 Victoria Island Boulevard, Suite 3B, Lagos',
  timezone: 'Africa/Lagos',
  botEnabled: true,
  businessHours: {
    monday: { open: '08:00', close: '19:00', closed: false },
    tuesday: { open: '08:00', close: '19:00', closed: false },
    wednesday: { open: '08:00', close: '19:00', closed: false },
    thursday: { open: '08:00', close: '19:00', closed: false },
    friday: { open: '08:00', close: '20:00', closed: false },
    saturday: { open: '09:00', close: '20:00', closed: false },
    sunday: { open: '10:00', close: '16:00', closed: false },
  },
  slotRules: {
    slotDurationMinutes: 45,
    bufferMinutes: 15,
    maxConcurrentBookings: 4,
  },
  welcomeMessage:
    '👋 Hello! Welcome to Brew & Botanica WhatsApp. I am your automated assistant. How can we delight you today?\n\n1️⃣ Browse Organic Teas & Pastries\n2️⃣ Book a Tea Tasting or Workshop\n3️⃣ Check Existing Order\n4️⃣ Talk to a Human Specialist',
  fallbackMessage:
    "I'm not quite sure I caught that. You can choose from our menu options or type 'agent' if you'd like our staff to step in!",
};

export const INITIAL_STAFF: StaffUser[] = [
  {
    id: 'staff_01',
    businessId: 'biz_01',
    name: 'Chioma Okafor',
    email: 'chioma@brewbotanica.com',
    role: 'OWNER',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    lastActiveAt: '2026-10-08T15:15:00Z',
  },
  {
    id: 'staff_02',
    businessId: 'biz_01',
    name: 'David Adebayo',
    email: 'david@brewbotanica.com',
    role: 'STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    lastActiveAt: '2026-10-08T14:40:00Z',
  },
  {
    id: 'staff_03',
    businessId: 'biz_01',
    name: 'Sarah Chen',
    email: 'sarah@brewbotanica.com',
    role: 'STAFF',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    lastActiveAt: '2026-10-08T12:00:00Z',
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'cust_01',
    businessId: 'biz_01',
    name: 'Tunde Bakare',
    phone: '+234 *** *** 4567',
    email: 'tunde.b@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    notes: 'VIP guest. Prefers oat milk in coffee drinks and gluten-free pastries.',
    tags: ['VIP', 'Coffee Lover', 'High Spender'],
    totalOrdersCount: 8,
    totalBookingsCount: 2,
    totalSpend: 245.5,
    firstSeenAt: '2026-06-12T09:00:00Z',
    lastSeenAt: '2026-10-08T14:55:00Z',
  },
  {
    id: 'cust_02',
    businessId: 'biz_01',
    name: 'Amara Nwosu',
    phone: '+234 *** *** 7820',
    email: 'amara.n@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    notes: 'Inquiring about bulk corporate gifting boxes.',
    tags: ['Corporate', 'Bulk Inquiries'],
    totalOrdersCount: 3,
    totalBookingsCount: 1,
    totalSpend: 420.0,
    firstSeenAt: '2026-08-01T11:20:00Z',
    lastSeenAt: '2026-10-08T15:02:00Z',
  },
  {
    id: 'cust_03',
    businessId: 'biz_01',
    name: 'Marcus Vance',
    phone: '+1 *** *** 3320',
    email: 'mvance@example.org',
    avatarUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    notes: 'Asked about botanical skincare range allergen certificate.',
    tags: ['Allergies', 'New Customer'],
    totalOrdersCount: 1,
    totalBookingsCount: 0,
    totalSpend: 34.0,
    firstSeenAt: '2026-10-07T16:00:00Z',
    lastSeenAt: '2026-10-08T13:40:00Z',
  },
  {
    id: 'cust_04',
    businessId: 'biz_01',
    name: 'Fatima Al-Hassan',
    phone: '+44 *** *** 8921',
    email: 'fatima.h@example.co.uk',
    avatarUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
    notes: 'Regular weekend tea ceremony attendee.',
    tags: ['Tea Club', 'Loyalty Tier 2'],
    totalOrdersCount: 5,
    totalBookingsCount: 4,
    totalSpend: 198.0,
    firstSeenAt: '2026-05-18T10:00:00Z',
    lastSeenAt: '2026-10-08T09:12:00Z',
  },
  {
    id: 'cust_05',
    businessId: 'biz_01',
    name: 'Kelechi Eze',
    phone: '+234 *** *** 1198',
    email: 'k.eze@example.com',
    avatarUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    notes: 'Ordered cold brew pouch batch yesterday.',
    tags: ['Local Delivery'],
    totalOrdersCount: 4,
    totalBookingsCount: 0,
    totalSpend: 86.0,
    firstSeenAt: '2026-09-02T14:10:00Z',
    lastSeenAt: '2026-10-06T18:22:00Z',
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_01',
    businessId: 'biz_01',
    name: 'Artisan Hibiscus Bloom Loose Tea (150g)',
    description: 'Sun-dried organic Nigerian hibiscus petals with orange peel and lemongrass hints.',
    price: 18.5,
    sku: 'TEA-HIB-01',
    imageUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=500&auto=format&fit=crop&q=80',
    category: 'Botanical Teas',
    inStock: true,
    stockQuantity: 42,
    disabled: false,
    createdAt: '2026-01-10T10:00:00Z',
    updatedAt: '2026-09-20T12:00:00Z',
  },
  {
    id: 'prod_02',
    businessId: 'biz_01',
    name: 'Cold Drip Reserve Ethiopian Yirgacheffe (500ml)',
    description: '18-hour cold steeped single origin coffee with jasmine and bergamot floral notes.',
    price: 14.0,
    sku: 'COF-DRIP-02',
    imageUrl: 'https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=500&auto=format&fit=crop&q=80',
    category: 'Craft Coffee',
    inStock: true,
    stockQuantity: 18,
    disabled: false,
    createdAt: '2026-02-14T10:00:00Z',
    updatedAt: '2026-10-01T08:00:00Z',
  },
  {
    id: 'prod_03',
    businessId: 'biz_01',
    name: 'Cardamom & Rose Sourdough Brioche (Box of 4)',
    description: 'Fermented sourdough brioche buns glazed with Persian rosewater syrup and pistachio crumbles.',
    price: 22.0,
    sku: 'PAS-BRIO-03',
    imageUrl: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=500&auto=format&fit=crop&q=80',
    category: 'Artisanal Bakery',
    inStock: true,
    stockQuantity: 9,
    disabled: false,
    createdAt: '2026-03-01T09:00:00Z',
    updatedAt: '2026-10-08T07:30:00Z',
  },
  {
    id: 'prod_04',
    businessId: 'biz_01',
    name: 'Matcha Ceremony Grade Uji Tin (50g)',
    description: 'First harvest stone-ground green tea powder sourced directly from Kyoto prefecture.',
    price: 32.0,
    sku: 'TEA-MAT-04',
    imageUrl: 'https://images.unsplash.com/photo-1536256263959-770b48d82b0a?w=500&auto=format&fit=crop&q=80',
    category: 'Botanical Teas',
    inStock: true,
    stockQuantity: 25,
    disabled: false,
    createdAt: '2026-04-12T11:00:00Z',
    updatedAt: '2026-08-15T14:00:00Z',
  },
  {
    id: 'prod_05',
    businessId: 'biz_01',
    name: 'Handcrafted Ceramic Tasting Cup',
    description: 'Locally fired speckled stoneware cup with heat-retaining matte earth glaze.',
    price: 26.0,
    sku: 'MERCH-CUP-05',
    imageUrl: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500&auto=format&fit=crop&q=80',
    category: 'Ceramics & Ware',
    inStock: false,
    stockQuantity: 0,
    disabled: false,
    createdAt: '2026-05-02T10:00:00Z',
    updatedAt: '2026-10-05T16:00:00Z',
  },
  {
    id: 'prod_06',
    businessId: 'biz_01',
    name: 'Botanical Infusion Glass Flask (750ml)',
    description: 'Double-walled borosilicate glass tumbler with built-in stainless fine mesh infuser basket.',
    price: 29.5,
    sku: 'MERCH-FLASK-06',
    imageUrl: 'https://images.unsplash.com/photo-1577937927133-66ef06acdf18?w=500&auto=format&fit=crop&q=80',
    category: 'Ceramics & Ware',
    inStock: true,
    stockQuantity: 14,
    disabled: false,
    createdAt: '2026-06-11T13:00:00Z',
    updatedAt: '2026-09-12T10:00:00Z',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord_01',
    businessId: 'biz_01',
    orderNumber: 'ORD-1092',
    customerId: 'cust_01',
    customer: INITIAL_CUSTOMERS[0],
    items: [
      {
        id: 'item_01',
        productId: 'prod_01',
        productName: 'Artisan Hibiscus Bloom Loose Tea (150g)',
        price: 18.5,
        quantity: 2,
        imageUrl: INITIAL_PRODUCTS[0].imageUrl,
      },
      {
        id: 'item_02',
        productId: 'prod_03',
        productName: 'Cardamom & Rose Sourdough Brioche (Box of 4)',
        price: 22.0,
        quantity: 1,
        imageUrl: INITIAL_PRODUCTS[2].imageUrl,
      },
    ],
    subtotal: 59.0,
    deliveryFee: 5.0,
    tax: 3.54,
    total: 67.54,
    status: 'PREPARING',
    paymentMethod: 'WHATSAPP_PAY',
    deliveryAddress: 'Apt 402, Oceanview Towers, Victoria Island, Lagos',
    notes: 'Please pack in eco-friendly gift box.',
    createdAt: '2026-10-08T13:10:00Z',
    updatedAt: '2026-10-08T13:45:00Z',
  },
  {
    id: 'ord_02',
    businessId: 'biz_01',
    orderNumber: 'ORD-1093',
    customerId: 'cust_02',
    customer: INITIAL_CUSTOMERS[1],
    items: [
      {
        id: 'item_03',
        productId: 'prod_04',
        productName: 'Matcha Ceremony Grade Uji Tin (50g)',
        price: 32.0,
        quantity: 3,
        imageUrl: INITIAL_PRODUCTS[3].imageUrl,
      },
      {
        id: 'item_04',
        productId: 'prod_06',
        productName: 'Botanical Infusion Glass Flask (750ml)',
        price: 29.5,
        quantity: 2,
        imageUrl: INITIAL_PRODUCTS[5].imageUrl,
      },
    ],
    subtotal: 155.0,
    deliveryFee: 10.0,
    tax: 9.3,
    total: 174.3,
    status: 'PAID',
    paymentMethod: 'CARD',
    deliveryAddress: 'Floor 7, Landmark Plaza, Lekki Phase 1',
    notes: 'Client gifting package. Needs invoice copy via WhatsApp.',
    createdAt: '2026-10-08T14:20:00Z',
    updatedAt: '2026-10-08T14:25:00Z',
  },
  {
    id: 'ord_03',
    businessId: 'biz_01',
    orderNumber: 'ORD-1090',
    customerId: 'cust_04',
    customer: INITIAL_CUSTOMERS[3],
    items: [
      {
        id: 'item_05',
        productId: 'prod_02',
        productName: 'Cold Drip Reserve Ethiopian Yirgacheffe (500ml)',
        price: 14.0,
        quantity: 2,
        imageUrl: INITIAL_PRODUCTS[1].imageUrl,
      },
    ],
    subtotal: 28.0,
    deliveryFee: 4.0,
    tax: 1.68,
    total: 33.68,
    status: 'COMPLETED',
    paymentMethod: 'WHATSAPP_PAY',
    deliveryAddress: 'Pickup in store',
    notes: 'Customer collected at 11am today.',
    createdAt: '2026-10-08T08:30:00Z',
    updatedAt: '2026-10-08T11:05:00Z',
  },
  {
    id: 'ord_04',
    businessId: 'biz_01',
    orderNumber: 'ORD-1088',
    customerId: 'cust_05',
    customer: INITIAL_CUSTOMERS[4],
    items: [
      {
        id: 'item_06',
        productId: 'prod_03',
        productName: 'Cardamom & Rose Sourdough Brioche (Box of 4)',
        price: 22.0,
        quantity: 2,
        imageUrl: INITIAL_PRODUCTS[2].imageUrl,
      },
    ],
    subtotal: 44.0,
    deliveryFee: 5.0,
    tax: 2.64,
    total: 51.64,
    status: 'PENDING',
    paymentMethod: 'BANK_TRANSFER',
    deliveryAddress: '24 Admiralty Way, Lekki',
    notes: 'Awaiting customer bank transfer confirmation slip.',
    createdAt: '2026-10-08T14:50:00Z',
    updatedAt: '2026-10-08T14:50:00Z',
  },
  {
    id: 'ord_05',
    businessId: 'biz_01',
    orderNumber: 'ORD-1085',
    customerId: 'cust_03',
    customer: INITIAL_CUSTOMERS[2],
    items: [
      {
        id: 'item_07',
        productId: 'prod_01',
        productName: 'Artisan Hibiscus Bloom Loose Tea (150g)',
        price: 18.5,
        quantity: 1,
        imageUrl: INITIAL_PRODUCTS[0].imageUrl,
      },
    ],
    subtotal: 18.5,
    deliveryFee: 5.0,
    tax: 1.11,
    total: 24.61,
    status: 'CANCELLED',
    paymentMethod: 'CASH_ON_DELIVERY',
    deliveryAddress: 'Cancelled by customer',
    notes: 'Customer changed mind and re-booked for tasting workshop instead.',
    createdAt: '2026-10-07T12:00:00Z',
    updatedAt: '2026-10-07T13:30:00Z',
  },
];

export const INITIAL_SERVICES: Service[] = [
  {
    id: 'srv_01',
    businessId: 'biz_01',
    name: 'Sensory Tea Tasting & Brewing Masterclass',
    description: 'A 45-minute curated flight of 5 rare single-origin botanicals with aroma pairing.',
    durationMinutes: 45,
    price: 35.0,
    color: '#059669', // Emerald
    disabled: false,
  },
  {
    id: 'srv_02',
    businessId: 'biz_01',
    name: 'Pour-Over Coffee Dialing Session',
    description: 'Private 1-on-1 barista calibration for home brewers using V60 and Kalita wave.',
    durationMinutes: 45,
    price: 40.0,
    color: '#d97706', // Amber
    disabled: false,
  },
  {
    id: 'srv_03',
    businessId: 'biz_01',
    name: 'Ceremonial Matcha Preparation Ritual',
    description: 'Traditional chasen whisking technique, water temperature control, and wagashi pairing.',
    durationMinutes: 30,
    price: 28.0,
    color: '#0284c7', // Sky
    disabled: false,
  },
  {
    id: 'srv_04',
    businessId: 'biz_01',
    name: 'Herbal Remedy Custom Blending Consultation',
    description: 'Consultation with our resident herbalist to build your personalized daily herbal formulation.',
    durationMinutes: 60,
    price: 55.0,
    color: '#7c3aed', // Purple
    disabled: false,
  },
];

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bkg_01',
    businessId: 'biz_01',
    bookingNumber: 'BKG-401',
    customerId: 'cust_01',
    customer: INITIAL_CUSTOMERS[0],
    serviceId: 'srv_01',
    service: INITIAL_SERVICES[0],
    startTime: '2026-10-08T16:00:00Z', // Today at 16:00
    endTime: '2026-10-08T16:45:00Z',
    status: 'CONFIRMED',
    notes: 'Bringing 1 colleague; prefers decaf herbal infusions.',
    assignedStaffId: 'staff_01',
    assignedStaff: INITIAL_STAFF[0],
    createdAt: '2026-10-06T11:00:00Z',
    updatedAt: '2026-10-06T11:00:00Z',
  },
  {
    id: 'bkg_02',
    businessId: 'biz_01',
    bookingNumber: 'BKG-402',
    customerId: 'cust_04',
    customer: INITIAL_CUSTOMERS[3],
    serviceId: 'srv_03',
    service: INITIAL_SERVICES[2],
    startTime: '2026-10-09T11:00:00Z', // Tomorrow at 11:00
    endTime: '2026-10-09T11:30:00Z',
    status: 'CONFIRMED',
    notes: 'Focus on ceremonial Grade A whisking posture.',
    assignedStaffId: 'staff_02',
    assignedStaff: INITIAL_STAFF[1],
    createdAt: '2026-10-07T14:15:00Z',
    updatedAt: '2026-10-07T14:15:00Z',
  },
  {
    id: 'bkg_03',
    businessId: 'biz_01',
    bookingNumber: 'BKG-403',
    customerId: 'cust_02',
    customer: INITIAL_CUSTOMERS[1],
    serviceId: 'srv_04',
    service: INITIAL_SERVICES[3],
    startTime: '2026-10-10T14:00:00Z', // Saturday at 14:00
    endTime: '2026-10-10T15:00:00Z',
    status: 'CONFIRMED',
    notes: 'Evaluating for executive corporate wellness retreat package.',
    assignedStaffId: 'staff_01',
    assignedStaff: INITIAL_STAFF[0],
    createdAt: '2026-10-08T10:00:00Z',
    updatedAt: '2026-10-08T10:00:00Z',
  },
  {
    id: 'bkg_04',
    businessId: 'biz_01',
    bookingNumber: 'BKG-398',
    customerId: 'cust_03',
    customer: INITIAL_CUSTOMERS[2],
    serviceId: 'srv_02',
    service: INITIAL_SERVICES[1],
    startTime: '2026-10-07T15:00:00Z', // Yesterday
    endTime: '2026-10-07T15:45:00Z',
    status: 'COMPLETED',
    notes: 'Great session, bought 2 bags of beans afterwards.',
    assignedStaffId: 'staff_02',
    assignedStaff: INITIAL_STAFF[1],
    createdAt: '2026-10-05T09:00:00Z',
    updatedAt: '2026-10-07T16:00:00Z',
  },
  {
    id: 'bkg_05',
    businessId: 'biz_01',
    bookingNumber: 'BKG-395',
    customerId: 'cust_05',
    customer: INITIAL_CUSTOMERS[4],
    serviceId: 'srv_01',
    service: INITIAL_SERVICES[0],
    startTime: '2026-10-06T10:00:00Z',
    endTime: '2026-10-06T10:45:00Z',
    status: 'CANCELLED',
    cancellationReason: 'Customer had flight conflict',
    assignedStaffId: 'staff_03',
    assignedStaff: INITIAL_STAFF[2],
    createdAt: '2026-10-04T12:00:00Z',
    updatedAt: '2026-10-05T18:00:00Z',
  },
];

export const INITIAL_FAQS: Faq[] = [
  {
    id: 'faq_01',
    businessId: 'biz_01',
    question: 'What are your delivery hours and locations?',
    answer:
      'We deliver within Victoria Island, Ikoyi, and Lekki Phase 1 between 9:00 AM and 6:00 PM daily. Same-day delivery applies to orders placed before 3:00 PM.',
    category: 'Delivery & Shipping',
    keywords: ['delivery', 'location', 'shipping', 'island', 'lekki', 'same day', 'hours'],
    usageCount: 142,
    updatedAt: '2026-09-15T10:00:00Z',
  },
  {
    id: 'faq_02',
    businessId: 'biz_01',
    question: 'How do I pay through WhatsApp?',
    answer:
      'You can pay directly via our WhatsApp checkout link supporting Debit Cards, Apple Pay, and instant bank transfers with automatic receipt generation.',
    category: 'Payment & Billing',
    keywords: ['payment', 'pay', 'checkout', 'card', 'transfer', 'receipt', 'bank'],
    usageCount: 98,
    updatedAt: '2026-09-20T11:00:00Z',
  },
  {
    id: 'faq_03',
    businessId: 'biz_01',
    question: 'Do you offer gluten-free and vegan bakery items?',
    answer:
      'Yes! All items marked with 🌿 in our catalog are 100% plant-based, and we bake gluten-free almond brioche every Wednesday and Saturday morning.',
    category: 'Products & Allergens',
    keywords: ['vegan', 'gluten free', 'allergies', 'plant based', 'dairy free', 'celiac'],
    usageCount: 67,
    updatedAt: '2026-10-02T14:00:00Z',
  },
  {
    id: 'faq_04',
    businessId: 'biz_01',
    question: 'What is your cancellation policy for tasting workshops?',
    answer:
      'You can reschedule or cancel with a full refund up to 4 hours before the session. Late cancellations can be credited towards artisanal retail goods.',
    category: 'Bookings & Workshops',
    keywords: ['cancel', 'reschedule', 'booking', 'refund', 'workshop', 'policy'],
    usageCount: 51,
    updatedAt: '2026-10-04T09:00:00Z',
  },
  {
    id: 'faq_05',
    businessId: 'biz_01',
    question: 'Can I order corporate or custom gift packages?',
    answer:
      'Absolutely. For orders over 10 gift sets, type "agent" to connect with our concierge team for custom branding, notes, and direct courier dispatch.',
    category: 'Corporate Gifting',
    keywords: ['corporate', 'bulk', 'gift', 'hampers', 'custom', 'branding'],
    usageCount: 39,
    updatedAt: '2026-10-06T15:30:00Z',
  },
];

export const INITIAL_OPTOUTS: OptOut[] = [
  {
    id: 'opt_01',
    businessId: 'biz_01',
    customerId: 'cust_09',
    customerName: 'Emeka Obi',
    phone: '+234 *** *** 6612',
    reason: 'Sent STOP command after promotional broadcast message',
    optedOutAt: '2026-09-18T14:22:00Z',
  },
  {
    id: 'opt_02',
    businessId: 'biz_01',
    customerId: 'cust_10',
    customerName: 'Grace Adeleke',
    phone: '+234 *** *** 9034',
    reason: 'Customer requested manual SMS instead of WhatsApp',
    optedOutAt: '2026-09-28T09:41:00Z',
  },
];

export const INITIAL_MESSAGES: Record<string, Message[]> = {
  conv_01: [
    {
      id: 'msg_101',
      conversationId: 'conv_01',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Hi! Can I change the delivery address for my order ORD-1092?',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T14:40:00Z',
    },
    {
      id: 'msg_102',
      conversationId: 'conv_01',
      direction: 'OUTBOUND',
      type: 'BUTTON',
      content: 'I see Order #ORD-1092 is currently PREPARING. Would you like to connect with a staff member to update the courier route?',
      options: [
        { id: 'opt_agent', title: 'Connect to Staff 🙋' },
        { id: 'opt_cancel', title: 'Keep Address' },
      ],
      deliveryStatus: 'READ',
      sentByBot: true,
      createdAt: '2026-10-08T14:40:15Z',
    },
    {
      id: 'msg_103',
      conversationId: 'conv_01',
      direction: 'INBOUND',
      type: 'BUTTON',
      content: 'Connect to Staff 🙋',
      selectedOptionId: 'opt_agent',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T14:41:00Z',
    },
    {
      id: 'msg_104',
      conversationId: 'conv_01',
      direction: 'OUTBOUND',
      type: 'TEXT',
      content: 'Understood! I have flagged this for our staff desk. An artisan specialist will be with you shortly.',
      deliveryStatus: 'READ',
      sentByBot: true,
      createdAt: '2026-10-08T14:41:02Z',
    },
    {
      id: 'msg_105',
      conversationId: 'conv_01',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Please let me know, as my meeting moved to Lekki Admiralty building.',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T14:42:20Z',
    },
  ],
  conv_02: [
    {
      id: 'msg_201',
      conversationId: 'conv_02',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Hello, we need 30 custom matcha and infusion gift tins for our tech summit next Thursday.',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T14:55:00Z',
    },
    {
      id: 'msg_202',
      conversationId: 'conv_02',
      direction: 'OUTBOUND',
      type: 'TEXT',
      content: '👋 Hi Amara! This is Chioma from Brew & Botanica. We would love to prepare this for your summit! Let me send you our corporate deck.',
      deliveryStatus: 'READ',
      sentByBot: false,
      senderStaffId: 'staff_01',
      createdAt: '2026-10-08T15:00:00Z',
    },
    {
      id: 'msg_203',
      conversationId: 'conv_02',
      direction: 'OUTBOUND',
      type: 'IMAGE',
      content: 'Here is our recent bespoke packaging tier for fintech partners.',
      mediaUrl: 'https://images.unsplash.com/photo-1576092768241-dec231879fc3?w=800&auto=format&fit=crop&q=80',
      deliveryStatus: 'READ',
      sentByBot: false,
      senderStaffId: 'staff_01',
      createdAt: '2026-10-08T15:01:00Z',
    },
    {
      id: 'msg_204',
      conversationId: 'conv_02',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'That looks stunning Chioma! Can we customize the ribbon seal with our company navy blue?',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T15:02:15Z',
    },
  ],
  conv_03: [
    {
      id: 'msg_301',
      conversationId: 'conv_03',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Does the Cardamom & Rose Brioche contain trace tree nuts? I have a severe pecan and walnut allergy.',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T13:35:00Z',
    },
    {
      id: 'msg_302',
      conversationId: 'conv_03',
      direction: 'OUTBOUND',
      type: 'TEXT',
      content: 'Our brioche is topped with pistachio crumbles, and our kitchen handles tree nuts. For safety, let me flag this for our head chef to confirm our cross-contact protocols.',
      deliveryStatus: 'DELIVERED',
      sentByBot: true,
      createdAt: '2026-10-08T13:35:10Z',
    },
    {
      id: 'msg_303',
      conversationId: 'conv_03',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Thank you, waiting for confirmation before placing order.',
      deliveryStatus: 'DELIVERED',
      sentByBot: false,
      createdAt: '2026-10-08T13:40:00Z',
    },
  ],
  conv_04: [
    {
      id: 'msg_401',
      conversationId: 'conv_04',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Hi! What time is my ceremonial matcha session tomorrow?',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T09:10:00Z',
    },
    {
      id: 'msg_402',
      conversationId: 'conv_04',
      direction: 'OUTBOUND',
      type: 'LIST',
      content: 'You are booked for "Ceremonial Matcha Preparation Ritual" tomorrow, Friday Oct 9, at 11:00 AM (Booking #BKG-402 with David Adebayo).',
      options: [
        { id: 'opt_add_calendar', title: '📅 Add to Calendar' },
        { id: 'opt_reschedule', title: '🔄 Reschedule' },
        { id: 'opt_directions', title: '📍 Get Directions' },
      ],
      deliveryStatus: 'READ',
      sentByBot: true,
      createdAt: '2026-10-08T09:10:15Z',
    },
    {
      id: 'msg_403',
      conversationId: 'conv_04',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Perfect, see you tomorrow at 11!',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-08T09:12:00Z',
    },
  ],
  conv_05: [
    {
      id: 'msg_501',
      conversationId: 'conv_05',
      direction: 'INBOUND',
      type: 'TEXT',
      content: 'Hello, received the cold brew batch yesterday. Delicious quality, thank you!',
      deliveryStatus: 'READ',
      sentByBot: false,
      createdAt: '2026-10-06T18:20:00Z',
    },
    {
      id: 'msg_502',
      conversationId: 'conv_05',
      direction: 'OUTBOUND',
      type: 'TEXT',
      content: "So thrilled to hear that Kelechi! Remember to keep it chilled below 4°C. Let us know whenever you'd like a refill bottle.",
      deliveryStatus: 'READ',
      sentByBot: false,
      senderStaffId: 'staff_02',
      createdAt: '2026-10-06T18:25:00Z',
    },
  ],
};

export const INITIAL_CONVERSATIONS: Conversation[] = [
  {
    id: 'conv_01',
    businessId: 'biz_01',
    customerId: 'cust_01',
    customer: INITIAL_CUSTOMERS[0],
    status: 'NEEDS_AGENT',
    assignedStaffId: undefined,
    lastMessage: INITIAL_MESSAGES['conv_01'][INITIAL_MESSAGES['conv_01'].length - 1],
    unreadCount: 2,
    needsAgentReason: 'Customer requested address change for in-flight order ORD-1092',
    lastCustomerMessageAt: '2026-10-08T14:42:20Z',
    createdAt: '2026-10-08T14:40:00Z',
    updatedAt: '2026-10-08T14:42:20Z',
  },
  {
    id: 'conv_02',
    businessId: 'biz_01',
    customerId: 'cust_02',
    customer: INITIAL_CUSTOMERS[1],
    status: 'HUMAN_HANDLING',
    assignedStaffId: 'staff_01',
    assignedStaff: INITIAL_STAFF[0],
    lastMessage: INITIAL_MESSAGES['conv_02'][INITIAL_MESSAGES['conv_02'].length - 1],
    unreadCount: 1,
    needsAgentReason: 'Corporate bulk order inquiry',
    lastCustomerMessageAt: '2026-10-08T15:02:15Z',
    createdAt: '2026-10-08T14:55:00Z',
    updatedAt: '2026-10-08T15:02:15Z',
  },
  {
    id: 'conv_03',
    businessId: 'biz_01',
    customerId: 'cust_03',
    customer: INITIAL_CUSTOMERS[2],
    status: 'NEEDS_AGENT',
    assignedStaffId: undefined,
    lastMessage: INITIAL_MESSAGES['conv_03'][INITIAL_MESSAGES['conv_03'].length - 1],
    unreadCount: 1,
    needsAgentReason: 'Severe nut allergy verification for bakery products',
    lastCustomerMessageAt: '2026-10-08T13:40:00Z',
    createdAt: '2026-10-08T13:35:00Z',
    updatedAt: '2026-10-08T13:40:00Z',
  },
  {
    id: 'conv_04',
    businessId: 'biz_01',
    customerId: 'cust_04',
    customer: INITIAL_CUSTOMERS[3],
    status: 'OPEN',
    assignedStaffId: undefined,
    lastMessage: INITIAL_MESSAGES['conv_04'][INITIAL_MESSAGES['conv_04'].length - 1],
    unreadCount: 0,
    lastCustomerMessageAt: '2026-10-08T09:12:00Z',
    createdAt: '2026-10-08T09:10:00Z',
    updatedAt: '2026-10-08T09:12:00Z',
  },
  {
    id: 'conv_05',
    businessId: 'biz_01',
    customerId: 'cust_05',
    customer: INITIAL_CUSTOMERS[4],
    status: 'RESOLVED',
    assignedStaffId: 'staff_02',
    assignedStaff: INITIAL_STAFF[1],
    lastMessage: INITIAL_MESSAGES['conv_05'][INITIAL_MESSAGES['conv_05'].length - 1],
    unreadCount: 0,
    lastCustomerMessageAt: '2026-10-06T18:20:00Z',
    createdAt: '2026-10-06T18:20:00Z',
    updatedAt: '2026-10-06T18:30:00Z',
  },
];
